---
output: pdf_document
---
# Introduction

Economic sanctions are widely used in foreign policy. In some cases, politicians impose sanctions simply to retaliate or signal disagreements, as in Turkey’s blockade against Armenia since the Nagorno-Karabakh conflict or the United States’ 1951 Trade Agreements Act that put the Soviet bloc outside of its Reciprocal Trade Program (Schelling 1958: 489-490). In other cases, politicians use sanctions to gain influence not through outright imposition, but through threats to impose them unless targets meet their demands. When the U.S. threatened Russia with sanctions unless it stopped supporting separatists in Ukraine in 2014, it sought to influence Russian policy by making it potentially too costly. If the economic cost of a potential sanction is perceived to entail high political cost on the leadership, the target leader will have an incentive to avoid it by conceding (Hirschman 1945: 17). 

How much a sanction’s economic costs translate into political costs is a function of a target’s domestic political institutions. Since a democratic society suffering under sanctions is in a better position to punish its leader or remove her or him from office, previous research suggests that sanctions in general “work” better against democracies (Brooks 2002: 1; Marinov 2005: 572-573; Lektzian and Souva 2007: 849). If that is correct, then politicians’ sanction practices are puzzling: almost all active U.S. sanctions target autocratic regimes.  If these targets are less likely to concede, sanctions might not be the best available investment of time and resources for politicians to achieve their foreign policy goals.

I argue that the solution to this puzzle lies in the fact that not all autocracies are equally resilient to sanctions threats. Specifically, personalist” regimes are resilient, and other non-democratic regimes under military or single-party rules respond to sanctions threats in ways that are more similar to their democratic counterparts. In other words, institutionalized autocracies produce constituencies that can pressure leaders to avoid economic hardship. Because a target can always avoid sanctions imposition by conceding to sender’s demand, studying sanctions threats also alleviate the challenge of selection effect. To paraphrase Schelling, as sanctions can be “most purposive and most successful when it is threatened and not used” (2008, 10), we might never observe the sanctions responsible for a target’s change in policy (Bueno de Mesquita and Smith 2012: 174; Noorudin 2002: 60; Smith 1995: 241) if we only study sanction impositions.

Drawing on a dataset of all threatened sanctions from 1945 to 2005,  I develop a “domestic audience” account to explain personalist targets’ resistance to sanctions threats. After taking potential confounding factors into consideration, targets are less likely to make policy concessions at threat stage compared to other regime types. The higher a target’s personalism score, the less likely it will concede. The results also hold when modeling target regime type in three categories: personalist, non-personalist, and democratic targets. While other scholars find sanction imposition to be more destabilizing on personalist targets (Escribà-Folch and Wright 2010: 334), this paper demonstrates empirically that the effectiveness of sanctions at imposition stage might not translate into useful threats: since personalist leaders has a smaller domestic audience size, they face little domestic punishment for policy failures, they can afford to stand firm against a sender which may or may not have the resolve to carry out its threat. Even if sanction imposition can increase their risks of being violently removed from power, this does not affect their threat stage calculus because the probability of successful elite coordination to is extremely low while the risk of being forcibly removed from office given a successful coordination is already high for these leaders. Moreover, the domestic political structure in personalist states also tends to select individuals who took “great risks to pursue power and were also lucky enough to survive” (Weeks 2014: 31). Even when facing foreign threats with potentially dire consequence, these leaders are expected to be risk-acceptant and demonstrate high resilience. With respect to foreign policy, this implies that personalist leaders can be relatively immune at threat stage. Therefore, using sanctions threats to leverage personalist targets could be a waste of time even if the same policy might work on democratic and non-personalist autocracies.

# Searching for A Sanction Effect

Situated between “words and war” (Marinov 2005: 565), sanctions are popular among politicians as they allow senders to coerce targets without resorting to military force. While the sanctions literature is extensive, one challenge for policy-makers is the multiple dimensionalities of sanction’s effectiveness. Some focus on sanctions’ merits as an alternative to use of force (Pape 1997: 90), others identify “circumstances in which economic sanctions can succeed” (Hufbauer et al 1990: 1), still others evaluate sanctions’ intended and unintended consequences, such as target regime change (Marinov 2005: 572-573) or human rights oppression following imposition (Drury and Peksen 2014: 463). In this article, I focus on the effect of “threatened” sanctions on a target’s policy behavior and bring clarity to the puzzle: what contributes to a target’s resistance against sanctions threats?  Are there systematic factors that allowed Russia to stand firm against sanctions threat in 2014, but not Guatemala in 1987? This setting allows me to address the common use of sanctions as a tool of foreign policy “compellence.”

Although the idea of explaining target resistance is not new, previous research tends to distinguish regime type only in “democratic” and “autocratic” black boxes, hence leaving the institutional variations among non-democracies unaddressed. In more recent studies, researchers show that not all autocracies are alike in their foreign policy behavior (for example, Weeks 2008: 44-49; Weiss 2014: 16-27). Especially important was Escribà-Folch and Wright’s (2010: 348-350) finding that once sanctions are imposed, leaders of personalist autocracies are more likely to be removed from power compared to leaders of other non-democracies. 

The result that autocratic targets respond to sanction’s destabilization differently due to their institutional variations invites further empirical inquiry: if autocratic regimes behave differently at sanction’s imposition stage as a result of their domestic political institutional variation, it is possible that such institutional variation also plays a role in autocratic leaders decision-making process when they are threatened with economic sanctions (i.e. at threat stage). Since strategic interaction is involved, there are reasons why the results in the two stages can be different, and addressing this would contribute to our understanding of the finding of Escribà-Folch and Wright (2010) – even if personalist institutions are more vulnerable to sanctions, they insulate leaders from responsibilities of failures and selecting a particular class of leaders who are less predictable and careless about the final outcome.

# Domestic Audience, Trade Dependence, and Target Resistance to Sanctions threats

I argue that the effectiveness of a sanctions threat is largely determined by two main factors: the size of a target’s domestic audience and its trade dependence on the sender. First, when a target leader is held responsible by a large domestic political audience, her or his preferences are constrained by the audience’s own political preferences.  Since sanctions are likely to cause economic damage to the general population, only leaders with a small domestic audience can isolate themselves from public pressure and stand firm against a sender’s demands. The logic here can be traced back to the selectorate theory (Bueno de Mesquita 2003; Peceny and Butler 2005: 570-575): a leader ensures her or his political survival by answering to the group that keeps her or him in power (the winning coalition). The implicit assumption here that the public is in general unwilling to stand the pain of sanctions is supported by empirical studies of sanction’s destabilization such as Marinov (2005: 572-573) and Escribà-Folch & Wright (2010: 348-350).  While it is possible that hostilities might help prop up target regimes in sanction impositions or use of force,  such situations seem to be rare and unlikely to introduce systematic bias. 

The literature on authoritarian regimes agrees that personalist dictators have the smallest domestic audience, whereas single-party and military regimes contain domestic audiences smaller than, but nonetheless similar to, those of democracies. In a personalist autocracy, the government is dominated by “a single individual” rather than by a military organization or a hegemonic party (Geddes 1999: 130). As a result, compared to a leader of a non-personalist autocracy, a personalist leader has more freedom in pursuing foreign policy goals at her or his will. A personalist leader is also more likely to be adventurous and revisionist in her or his foreign policy position because, as elaborated by Weeks (2014: 29-30), personalist leaders have greater discretion over the distribution of “potential spoils” from their policies. Even in the wake of a foreign policy failure, personalist leaders could face only little political punishment: because their regimes are weakly institutionalized, the probability of successful coordination among political elites to remove a personalist leader from power is very low, and scholars find makes personalist leaders comparatively invulnerable to negative foreign policy consequence such as war outcomes (Croco and Weeks 2016: 594-602). 

One potential counter-argument is that even if elite coordination against personalist leaders is unlikely to succeed, it still has a deterrent effect on the leadership because of its extremely high risk: once a personalist leader is removed from power, she or he is much more likely to be removed irregularly and violently compared to leaders in other autocracies (Escribà-Folch and Wright 2010: 348-350). However, research on leaders and international conflict suggests that such risk provides little deterrent to personalist leaders, as their risk of being forcibly removed from office is already high (Chiozza and Goemans 2011: 28). Under sanctions threats, this allows a personalist leader to stand firm regardless of the potential costs to the country. An illustrative example is Saddam Hussein’s reaction to the sanctions imposed by the UN Security Council. Although Iraq’s total import and exports decreased by a stunning 38.5 billion from 1980 to 1996 (Brooks 2002: 1) and the population’s suffering was beyond description, he was in no way constrained by domestic population or elites and there were no visible domestic political consequences for the economic loss caused by his policy.

In addition to giving its leader a higher share of the spoils after a success and shielding her or him from negative political consequence after a failure, personalist institutions also introduce non-rational sources of sanctions resistance as the selection of leadership under such a regime favors leaders with a particular “tyrannical” personality colored by international ambition (Week 2014: 29-31), supremacy (Rosen 2005: 135-136), and self-image (Glad 2002: 3). Moreover, the general argument that career paths of political leaders tend to select individuals with “positive illusions” (Johnson 2004: 24) and overconfidence (Taylor and Brown 1988: 199) into high office can makes an even stronger case for personalist leaders, as they need to take “great risks to pursue power and were also lucky enough to survive” (Weeks 2014: 31). In sum, even when facing sanctions threat with potentially costly consequence, personalist leaders are more likely to stand firm compared to leaders of other regimes.

The domestic audience account presented above also draws insight from the literature on autocratic regimes and use of force. For instance, previous research found that among non-democratic leaders, personalist dictators are the most likely to initiate disputes with democratic states (Reiter and Stam 2003: 333). Military operations are much more costly than economic sanctions and one would expect leaders to be more cautious in their decisions to initiate them. Despite losing a higher proportion of the wars they start, “personalist bosses” are still more risk-acceptant compared to leaders in other regimes who must avoid risky military ventures in order to stay in power. As a result, they “initiate conflict more frequently, lose a higher proportion of the wars they start, and yet survive in office at a remarkable rate in the wake of defeat” (Weeks 2014: 7) compared to democracies and other types of autocracies.

Three examples are used to illustrate how domestic audience size is able to explain threat stage outcomes for three sanctions threats issued by the United States: (a) its failed sanctions threat against Panama (personalist) in 1987, (b) its successful threat against Japan (democratic) in 1994, and (c) its successful sanctions threat against Guatemala (non-personalist autocracy) in 1993. 

(a) The U.S.’s sanctions threat against Panama started on August 8, 1987, when Rep. Mel Levine introduced H.R.3214 in the House against Panamanian military commander Manuel Noriega’s regime. The Noriega regime was a military-personalist autocracy with a personalist index of 1. Consistent with domestic audience theory, the institutional selection of leadership under personalist rule selected a brutal and recalcitrant dictator, and the small domestic audience size gave Noriega little reason to cave in. Noriega rose to power “through a long and calculated career of corruption, deceit, and betrayal” (Witt 1990: ii) and was involved in human rights abuses, narcotics trafficking and money laundering (Sullivan and Rivas 2008: 26-27). Despite Panama’s close economic relationship with the U.S., which included foreign aid, a bilateral investment treaty in 1982, and its access to U.S. markets from the Caribbean Basin Initiative (CBI) in 1984, dependence failed to make a difference in Noriega’s firm position against U.S. threat. After the imposition of unsuccessful sanctions for two years, George H. W. Bush ordered U.S. military intervention, known as Operation Just Cause, and removed Noriega from power by force. 

(b) In the U.S.-Japan example, sanctions threat was issued by U.S. Trade Representative Mickey Kantor in October 1993 conditioned on Japan’s opening of its construction market to foreign competition.  Prior to this episode, both Reagan and Bush administration had sought to open Japan’s twenty-billion market of construction services and the issue has been a “lingering irritant in U.S.-Japanese trade relations.”  As U.S.’s key democratic allies, Japan has had deep economic ties with the United States. Although initially reluctant to open the market under U.S. pressure, the Japanese government under Prime Minister Morihiro Hosokawa conceded in January 1994, three months after the sanctions threat and a month before a scheduled meeting between Clinton and Hosokawa.

(c) The U.S. sanctions threat against Guatemala in May 1993 was a response to President Jorge Serrano Elias’s self-coup when he dissolved Congress and Supreme Court and imposed press censorship. At that time, Guatemala has been under an indirect military rule for 7 years based on Geddes’s classification. With a relatively larger domestic audience size compared to personalist regimes and a close economic relationship with the U.S., domestic audience theory predicts that Guatemala’s leaders are more likely to concede as they are more vulnerable to pressures from the general population. This was indeed the case: while other Latin American states also moved fast to address this issue multilaterally, scholars find that the most powerful factor explaining the outcome was the U.S.’s threat to withdraw Guatemala’s trade benefits under the General System of Preferences (Brett 2008: 45). This potentially devastating cost led the business community to use their influence with their allies within the military and join other civil society groups to successfully pressured Serrano from power. 

Based on this preceding discussions and examples, I test the following two hypotheses:

Hypothesis 1a: when sender-target trade dependence is low, personalist targets are as likely as to make policy concessions compared to democracies and other autocracies when threatened with economic sanctions.

Hypothesis 1b: when sender-target trade dependence is high, personalist targets are, on average, less likely to make policy concessions compared to democracies and other autocracies when threatened with economic sanctions.

While the main theoretical focus is the domestic political institution of the target regime, including target dependence is helpful in setting a scope condition of when personalist targets are expected to behave in a systematically different way compared to other types of targets. Cases in which a target is threatened by a sender with which it had little or no trade at all might be less relevant to the mechanisms proposed here – since senders in these cases cannot inflict costly economic consequence on the general population through cutting down trade, the size of domestic audience in democracies, personalist regimes, and other autocracies does not generate useful predictions on how targets respond compared to high-trade-dependence scenarios. 



